# Generated by Django 3.1.1 on 2021-05-02 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(default='AVAILABLE', max_length=100, primary_key=True, serialize=False),
        ),
    ]
