# Generated by Django 3.1.1 on 2021-05-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0003_auto_20210502_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('SOLD OUT', 'Sold Out')], default='AVAILABLE', max_length=100, primary_key=True, serialize=False),
        ),
    ]
