# Generated by Django 3.1.1 on 2021-05-02 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0005_auto_20210502_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brands',
            fields=[
                ('brand', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('shoe_id', models.AutoField(primary_key=True, serialize=False)),
                ('shoe_image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Shoe Image')),
                ('shoe_name', models.CharField(blank=True, max_length=100, null=True)),
                ('price', models.FloatField(blank=True, null=True, verbose_name='Price')),
                ('colors', models.CharField(blank=True, max_length=100, null=True, verbose_name='Colors Available')),
                ('shoe_size_from', models.IntegerField(blank=True, null=True, verbose_name='Shoe-Size-From')),
                ('shoe_size_to', models.IntegerField(blank=True, null=True, verbose_name='Shoe-Size-To')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Date Added')),
                ('shoe_brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nitto1.brands')),
            ],
        ),
    ]
