# Generated by Django 3.1.1 on 2021-05-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0006_brands_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shoe_image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Shoe Image'),
        ),
    ]
