# Generated by Django 3.1.1 on 2021-05-03 08:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Nitto1', '0007_auto_20210502_1454'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('county', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='products',
            name='shoe_availability',
            field=models.ForeignKey(default='Available', on_delete=django.db.models.deletion.CASCADE, to='Nitto1.productstatus'),
        ),
        migrations.AddField(
            model_name='products',
            name='shoe_sex',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Nitto1.productcategory'),
        ),
        migrations.AlterField(
            model_name='productcategory',
            name='category',
            field=models.CharField(choices=[('NONE', 'None'), ('MALE', 'Male'), ('FEMALE', 'Female')], default='NONE', max_length=100, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('profile_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.IntegerField(blank=True, null=True, verbose_name='Profile Image')),
                ('email', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.IntegerField(default=2547, null=True)),
                ('registration_date', models.DateTimeField(auto_now_add=True, verbose_name='Date Registered')),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Nitto1.productcategory')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
