# Generated by Django 3.1.1 on 2021-05-03 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0008_auto_20210503_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sex',
            field=models.ForeignKey(default='None', on_delete=django.db.models.deletion.CASCADE, to='Nitto1.productcategory'),
        ),
    ]
