# Generated by Django 3.1.1 on 2021-05-03 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0009_auto_20210503_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='shoe_sex',
            field=models.ForeignKey(default='NONE', on_delete=django.db.models.deletion.CASCADE, to='Nitto1.productcategory'),
        ),
    ]
