# Generated by Django 3.1.1 on 2021-05-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0011_auto_20210503_1207'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='county',
            field=models.ForeignKey(default='Nairobi', on_delete=django.db.models.deletion.CASCADE, to='Nitto1.county'),
        ),
    ]
