# Generated by Django 3.1.1 on 2021-05-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nitto1', '0013_auto_20210503_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(default='2547', max_length=100, null=True),
        ),
    ]
